### ISSUE TITLE
Documentation Access

### ISSUE THREAD

**Issue by akhil-rasheed** [smartestapp/smart-ml#9]
The Google Drive links have restricted access. Request for access haven't been approved even after repeated attempts for weeks :( 
Would it possible to make it public somehow? Any help on this would be greatly appreciated.

**Comment by uzaymacar** [comment]
Hi @akhil-rasheed, I've just added you to the GDrive folder. Let me know if there are any issues accessing.

Please ask any other inquiries from here (GH issues) as it's easier for us to take notice -- thanks!
